eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultzone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 9090
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: company-service
        predicates:
        - Path=/api/v1.0/market/company/**
        uri: lb://COMPANY-SERVICE
      - id: stock-service
        predicates:
        - Path=/api/v1.0/market/stock/**
        uri: lb://STOCK-SERVICE
